version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: daily
    ports:
      - "3307:3306"
